# Generated by Django 6.0.6 on 2026-06-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Название")),
                (
                    "poster",
                    models.ImageField(upload_to="posters/", verbose_name="Постер"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                ("genre", models.CharField(max_length=50, verbose_name="Жанр")),
                (
                    "duration",
                    models.PositiveIntegerField(verbose_name="Длительность (мин)"),
                ),
                (
                    "age_limit",
                    models.PositiveIntegerField(verbose_name="Возрастное ограничение"),
                ),
                ("language", models.CharField(max_length=50, verbose_name="Язык")),
                ("trailer", models.URLField(verbose_name="Трейлер (Youtube)")),
                ("release_start", models.DateField(verbose_name="Дата начала проката")),
                (
                    "release_end",
                    models.DateField(verbose_name="Дата окончания проката"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("showing", "В прокате"),
                            ("soon", "Скоро"),
                            ("archive", "Архив"),
                        ],
                        max_length=30,
                        verbose_name="Статус",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "Фильм",
                "verbose_name_plural": "Фильмы",
            },
        ),
    ]
