# Generated by Django 6.0.6 on 2026-06-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_contacts"),
    ]

    operations = [
        migrations.AddField(
            model_name="contacts",
            name="telegram",
            field=models.URLField(blank=True, verbose_name="Телеграмм"),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="instagram",
            field=models.URLField(blank=True, verbose_name="Инстаграм"),
        ),
    ]
