# Generated by Django 6.0.6 on 2026-06-16 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Название")),
                (
                    "seats_count",
                    models.PositiveIntegerField(verbose_name="Количество мест"),
                ),
                (
                    "hall_type",
                    models.CharField(
                        choices=[
                            ("standart", "Стандарт"),
                            ("vip", "VIP"),
                            ("3d", "3D"),
                        ],
                        max_length=30,
                        verbose_name="Тип зала",
                    ),
                ),
                (
                    "scheme",
                    models.ImageField(
                        upload_to="halls/schemes/", verbose_name="Схема зала"
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "Зал",
                "verbose_name_plural": "Залы",
            },
        ),
    ]
